### ISSUE TITLE
Upgrade to EE4/5?

### ISSUE THREAD

**Issue by kemmerly** [EpicVoyage/ee2-dandycat#1]
Hi Chris,

I'm using your module Dandy Cat on an EE2 site. It's very useful – thanks for making it.

I'm trying to upgrade this site to ExpressionEngine 5 and was wondering if you had any plans on updating the module to work with EE 4/5?

Thanks!

**Comment by EpicVoyage** [comment]
Hey Kevin,

Thanks for reaching out and your appreciation of my work! All of my EE support is currently on EE 1 & 2 sites (which need to be upgraded soon). From a brief look at the upgrade notes on EE add-ons, it should be fairly easy to migrate Dandy Cat.

I will try to take a look at the underlying database changes in the next week or two.

Chris

**Comment by EpicVoyage** [comment]
Hey Kevin,

Commit 05a0a282222be46e52f7df1f55ffd6506517cc5e brings this add-on into the EE5 world. My intitial tests look good.
